# Generated by Django 2.2.6 on 2019-10-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191030_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='post',
            name='averageRating',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=3),
            preserve_default=False,
        ),
    ]
