# Generated by Django 2.2.6 on 2019-11-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191103_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Journalist'),
        ),
    ]
